'use client';

import { useMemo, useState } from 'react';
import {
  Activity, ArrowLeftRight, BellRing, BusFront, Check, ChevronDown, CircleDot,
  Clock3, Edit3, Gauge, LayoutDashboard, LocateFixed, LogOut, Map as MapIcon,
  MapPin, Menu, MoreHorizontal, Navigation, PencilRuler, Phone, Plus, Radio,
  Route, Search, ShieldCheck, Trash2, Undo2, Users, X,
} from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Badge } from '@/components/ui/badge';
import { Input } from '@/components/ui/input';

type View = 'passenger' | 'driver' | 'admin';
type AdminTab = 'overview' | 'routes' | 'vehicles' | 'gps';

const routes = [
  { code: '05', name: 'Cicaheum — Ciroyom', via: 'Jl. Ahmad Yani', stops: 14, color: '#ff5a47', active: 3, fleet: 12, path: 'M164 649 C260 575 255 475 365 430 C477 385 470 278 590 268 C727 256 743 375 865 337 C951 310 985 224 1052 176' },
  { code: '03', name: 'Sadang Serang — Caringin', via: 'Jl. Dipatiukur', stops: 11, color: '#2970ff', active: 5, fleet: 9, path: 'M90 208 C220 245 310 354 435 337 C592 316 620 449 760 470 C890 490 950 586 1120 598' },
  { code: '10', name: 'Cicadas — Elang', via: 'Jl. Asia Afrika', stops: 16, color: '#e9a319', active: 4, fleet: 15, path: 'M160 560 C300 520 350 590 480 514 C600 443 690 498 790 410 C900 314 1010 342 1100 238' },
];

const initialVehicles = [
  { plate: 'D 1924 UA', driver: 'Asep Suhendar', route: '05', gps: 'GPS-TL-001', status: 'Aktif' },
  { plate: 'D 1842 UB', driver: 'Dadang Hidayat', route: '05', gps: 'GPS-TL-002', status: 'Aktif' },
  { plate: 'D 1721 UC', driver: 'Ujang Rohman', route: '05', gps: 'GPS-TL-008', status: 'Istirahat' },
  { plate: 'D 2011 VD', driver: 'Rizal Maulana', route: '03', gps: 'GPS-TL-011', status: 'Aktif' },
];

const vehiclePins = [
  { id: 'D 1924 UA', x: 36, y: 29, eta: '3 mnt' }, { id: 'D 1842 UB', x: 58, y: 51, eta: '7 mnt' }, { id: 'D 1721 UC', x: 77, y: 68, eta: '11 mnt' },
];

function Logo({ compact = false }: { compact?: boolean }) {
  return <div className="flex items-center gap-2.5"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-coral text-white shadow-sm"><Navigation className="size-5" /></span>{!compact && <div><p className="text-[9px] font-bold uppercase tracking-[.18em] text-slate-400">Transportation Link</p><p className="font-extrabold leading-tight text-ink">Traslink</p></div>}</div>;
}

function MapCanvas({ routeIndex = 0, driver = false, editor = false }: { routeIndex?: number; driver?: boolean; editor?: boolean }) {
  const route = routes[routeIndex];
  return <div className="absolute inset-0 overflow-hidden bg-[#e8eee9]">
    <div className="absolute inset-0 map-grid" />
    <svg className="absolute inset-0 h-full w-full" viewBox="0 0 1200 800" preserveAspectRatio="xMidYMid slice" aria-label={`Peta trayek ${route.name}`}>
      <g className="map-roads" fill="none" strokeLinecap="round"><path d="M-80 150 C180 210 300 145 520 170 S870 225 1300 105" strokeWidth="34" /><path d="M145 -40 C200 160 190 310 280 470 S405 680 470 860" strokeWidth="25" /><path d="M720 -20 C670 190 745 330 700 510 S610 690 650 850" strokeWidth="30" /><path d="M-80 610 C180 540 340 590 530 570 S880 470 1280 560" strokeWidth="24" /><path d="M410 -20 C440 180 370 310 465 410 S740 520 930 800" strokeWidth="17" /><path d="M900 30 C860 180 920 310 1110 390" strokeWidth="18" /></g>
      <g fill="none" strokeLinecap="round" strokeLinejoin="round"><path d={route.path} stroke="white" strokeWidth="18" opacity=".92" /><path d={route.path} stroke={route.color} strokeWidth="10" /></g>
      {editor && [[164,649],[365,430],[590,268],[865,337],[1052,176]].map(([x,y],i)=><g key={x}><circle cx={x} cy={y} r="16" fill="white" stroke={route.color} strokeWidth="4"/><text x={x} y={y+4} textAnchor="middle" fontSize="11" fontWeight="800" fill="#10221e">{i+1}</text></g>)}
    </svg>
    {!editor && vehiclePins.map((v, i) => <div key={v.id} className="absolute z-10 -translate-x-1/2 -translate-y-1/2" style={{ left: `${v.x + routeIndex * 2}%`, top: `${v.y - routeIndex}%` }}><div className="grid size-10 place-items-center rounded-full border-4 border-white bg-[#163d35] text-white shadow-lg"><BusFront className="size-4" /></div><span className="absolute left-1/2 top-10 -translate-x-1/2 whitespace-nowrap rounded-md bg-slate-950 px-2 py-1 text-[10px] font-bold text-white shadow">{v.eta}</span></div>)}
    {driver && <><PickupPin x="48%" y="42%" name="Nadia" distance="120 m" /><PickupPin x="69%" y="60%" name="Bima" distance="650 m" /></>}
  </div>;
}

function PickupPin({ x, y, name, distance }: { x: string; y: string; name: string; distance: string }) {
  return <div className="pickup-pulse absolute z-20 -translate-x-1/2 -translate-y-1/2" style={{ left:x, top:y }}><div className="rounded-xl bg-white p-1.5 pr-3 shadow-map"><div className="flex items-center gap-2"><span className="grid size-8 place-items-center rounded-lg bg-coral text-white"><BellRing className="size-4" /></span><span><b className="block text-xs">{name}</b><span className="text-[10px] text-slate-500">{distance}</span></span></div></div></div>;
}

function TopNav({ view, setView }: { view: View; setView: (v: View) => void }) {
  return <header className="absolute inset-x-0 top-0 z-40 flex items-center justify-between px-4 py-4 md:px-7"><div className="rounded-2xl border border-white/70 bg-white/90 p-2 pr-4 shadow-map backdrop-blur-xl"><Logo /></div><nav className="flex items-center gap-1 rounded-xl border border-white/70 bg-white/90 p-1 shadow-map backdrop-blur-xl">{([['passenger','Penumpang'],['driver','Supir'],['admin','Admin']] as const).map(([key,label])=><button key={key} onClick={()=>setView(key)} className={`rounded-lg px-3 py-2 text-xs font-semibold transition md:px-4 ${view===key?'bg-ink text-white':'text-slate-600 hover:bg-slate-100'}`}>{label}</button>)}</nav></header>;
}

function PassengerView({ setView }: { setView: (v: View) => void }) {
  const [routeIndex, setRouteIndex] = useState(0); const [direction, setDirection] = useState<'A'|'B'>('A'); const [pickup, setPickup] = useState(false); const [nearRoute, setNearRoute] = useState(true); const [open, setOpen] = useState(false);
  const route = routes[routeIndex];
  return <main className="relative h-dvh min-h-[680px] overflow-hidden text-slate-950"><MapCanvas routeIndex={routeIndex}/><TopNav view="passenger" setView={setView}/>
    <section className="absolute left-1/2 top-24 z-30 w-[calc(100%-2rem)] max-w-xl -translate-x-1/2 rounded-[22px] border border-white/80 bg-white/94 p-3 shadow-map backdrop-blur-xl">
      <button onClick={()=>setOpen(!open)} className="flex w-full items-center justify-between rounded-xl px-2 py-1.5 text-left"><span className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl font-black" style={{background:`${route.color}15`, color:route.color}}>{route.code}</span><span><b className="block text-sm">{route.name}</b><span className="text-xs text-slate-500">Via {route.via} · {route.stops} halte</span></span></span><ChevronDown className={`size-4 text-slate-400 transition ${open?'rotate-180':''}`}/></button>
      {open && <div className="mt-2 space-y-1 border-t pt-2">{routes.map((r,i)=><button key={r.code} onClick={()=>{setRouteIndex(i);setOpen(false)}} className={`flex w-full items-center gap-3 rounded-xl p-2 text-left hover:bg-slate-50 ${i===routeIndex?'bg-slate-50':''}`}><span className="grid size-8 place-items-center rounded-lg text-xs font-black text-white" style={{background:r.color}}>{r.code}</span><span className="flex-1 text-xs font-semibold">{r.name}</span>{i===routeIndex&&<Check className="size-4 text-emerald-600"/>}</button>)}</div>}
      <div className="mt-2 grid grid-cols-[1fr_auto_1fr] items-center rounded-xl bg-slate-100 p-1"><button onClick={()=>setDirection('A')} className={`rounded-lg px-3 py-2 text-xs font-bold ${direction==='A'?'bg-white shadow-sm':'text-slate-500'}`}>Ke {route.name.split(' — ')[1]}</button><ArrowLeftRight className="size-3.5 text-slate-400"/><button onClick={()=>setDirection('B')} className={`rounded-lg px-3 py-2 text-xs font-bold ${direction==='B'?'bg-white shadow-sm':'text-slate-500'}`}>Ke {route.name.split(' — ')[0]}</button></div>
    </section>
    <div className="absolute bottom-61 right-4 z-20 md:bottom-8 md:right-7"><Button onClick={()=>setNearRoute(!nearRoute)} variant="outline" size="icon-lg" className={`rounded-xl border-white bg-white shadow-map ${nearRoute?'text-coral':'text-slate-400'}`} aria-label="Simulasikan lokasi"><LocateFixed/></Button></div>
    <section className="absolute inset-x-3 bottom-3 z-30 mx-auto max-w-3xl rounded-[26px] border border-white/80 bg-white/96 p-4 shadow-sheet backdrop-blur-xl md:bottom-6 md:p-5"><div className="mx-auto mb-3 h-1 w-10 rounded-full bg-slate-200 md:hidden"/><div className="flex items-start justify-between gap-3"><div className="flex gap-3"><div className="grid size-12 shrink-0 place-items-center rounded-2xl bg-ink text-white"><BusFront className="size-6"/></div><div><div className="flex items-center gap-2"><h2 className="font-extrabold">Angkot {route.code}</h2><Badge className="bg-emerald-50 text-emerald-700">{route.active} aktif</Badge></div><p className="mt-0.5 text-xs text-slate-500">{route.name.replace(' — ',' · ')}</p></div></div><div className="text-right"><p className="text-xs text-slate-400">Terdekat</p><p className="text-lg font-black text-coral">3 menit</p></div></div>
      <div className="my-4 grid grid-cols-3 divide-x divide-slate-100 rounded-xl bg-slate-50 py-3 text-center"><Info icon={<Clock3/>} text="05.00–21.00"/><Info icon={<Users/>} text="12 kursi"/><Info icon={<ShieldCheck/>} text="Terverifikasi"/></div>
      <Button disabled={!nearRoute} onClick={()=>setPickup(!pickup)} className={`h-12 w-full rounded-xl text-sm font-bold ${pickup?'bg-rose-50 text-[#e54836] hover:bg-rose-100':'bg-coral text-white hover:bg-[#ec4b39]'}`}><MapPin/> {pickup?'Batal Jemput di Sini':'Jemput di Sini'}</Button><p className={`mt-2 text-center text-[11px] ${nearRoute?'text-slate-400':'font-semibold text-amber-600'}`}>{nearRoute?'Kamu berada 18 m dari jalur · Sinyal akan terlihat oleh supir':'Kamu terlalu jauh dari jalur · Dekati jalur untuk meminta jemput'}</p>
    </section>
  </main>;
}

function Info({icon,text}:{icon:React.ReactNode;text:string}) { return <div><span className="mx-auto mb-1 block w-fit text-slate-400 [&_svg]:size-4">{icon}</span><b className="text-xs">{text}</b></div>; }

function DriverView({setView}:{setView:(v:View)=>void}) {
  const [online,setOnline]=useState(true); const [accepted,setAccepted]=useState<string[]>([]);
  const signals=[{name:'Nadia P.',distance:'120 m',wait:'2 menit',phone:'••• 4821'},{name:'Bima A.',distance:'650 m',wait:'5 menit',phone:'••• 1730'}];
  return <main className="relative h-dvh min-h-[700px] overflow-hidden"><MapCanvas driver/><TopNav view="driver" setView={setView}/><div className="absolute left-4 top-24 z-30 rounded-2xl bg-ink p-3 text-white shadow-map md:left-7"><div className="flex items-center gap-3"><span className={`size-2.5 rounded-full ${online?'bg-emerald-400 animate-pulse':'bg-slate-500'}`}/><div><p className="text-[10px] text-white/55">D 1924 UA · Trayek 05</p><b className="text-sm">{online?'Sedang beroperasi':'Tidak aktif'}</b></div><button onClick={()=>setOnline(!online)} className={`ml-3 rounded-lg px-3 py-1.5 text-xs font-bold ${online?'bg-white/12':'bg-emerald-500'}`}>{online?'Selesai':'Mulai'}</button></div></div>
    <section className="absolute inset-x-3 bottom-3 z-30 mx-auto max-w-2xl rounded-[26px] border border-white/80 bg-white/96 p-4 shadow-sheet backdrop-blur-xl md:inset-x-auto md:bottom-6 md:left-7 md:w-[390px]"><div className="mb-3 flex items-center justify-between"><div><p className="text-[10px] font-bold uppercase tracking-widest text-coral">Permintaan jemput</p><h2 className="text-lg font-extrabold">2 penumpang di depan</h2></div><Badge className="bg-coral text-white"><Radio className="size-3"/> Live</Badge></div><div className="space-y-2">{signals.map((s)=><div key={s.name} className="rounded-2xl border bg-white p-3"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-full bg-[#fff0ed] font-black text-coral">{s.name[0]}</span><div className="min-w-0 flex-1"><b className="text-sm">{s.name}</b><p className="text-xs text-slate-500">{s.distance} · menunggu {s.wait}</p></div>{accepted.includes(s.name)?<Badge className="bg-emerald-50 text-emerald-700"><Check/>Diterima</Badge>:<Button onClick={()=>setAccepted([...accepted,s.name])} size="sm" className="bg-ink">Jemput</Button>}</div>{accepted.includes(s.name)&&<div className="mt-3 flex gap-2 border-t pt-3"><Button variant="outline" className="flex-1"><Phone/> {s.phone}</Button><Button className="flex-1 bg-coral"><Navigation/> Navigasi</Button></div>}</div>)}</div><p className="mt-3 flex items-center justify-center gap-1 text-[11px] text-slate-400"><Gauge className="size-3"/> Diperbarui 4 detik lalu</p></section>
  </main>;
}

function StatCard({icon,label,value,change}:{icon:React.ReactNode;label:string;value:string;change:string}) { return <div className="rounded-2xl border bg-white p-4 shadow-sm"><div className="mb-4 flex items-center justify-between"><span className="grid size-9 place-items-center rounded-xl bg-slate-100 text-ink [&_svg]:size-4">{icon}</span><Badge className="bg-emerald-50 text-emerald-700">{change}</Badge></div><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-2xl font-black tracking-tight">{value}</p></div>; }

function AdminView({setView}:{setView:(v:View)=>void}) {
  const [tab,setTab]=useState<AdminTab>('overview'); const [vehicles,setVehicles]=useState(initialVehicles); const [query,setQuery]=useState(''); const [showForm,setShowForm]=useState(false); const [routeFilter,setRouteFilter]=useState('Semua'); const [toast,setToast]=useState('');
  const filtered=useMemo(()=>vehicles.filter(v=>(routeFilter==='Semua'||v.route===routeFilter)&&`${v.plate} ${v.driver}`.toLowerCase().includes(query.toLowerCase())),[vehicles,query,routeFilter]);
  function addVehicle(){setVehicles([...vehicles,{plate:'D 2088 TL',driver:'Sopir Baru',route:'03',gps:'GPS-TL-016',status:'Aktif'}]);setShowForm(false);setToast('Angkot baru berhasil ditambahkan');setTimeout(()=>setToast(''),2500)}
  return <main className="min-h-dvh bg-[#f4f7f5] text-ink"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col border-r bg-white p-4 lg:flex"><Logo/><div className="mt-9 space-y-1"><p className="mb-2 px-3 text-[10px] font-bold uppercase tracking-widest text-slate-400">Workspace</p>{([['overview','Ringkasan',<LayoutDashboard key="i"/>],['routes','Trayek & Rute',<Route key="i"/>],['vehicles','Data Angkot',<BusFront key="i"/>],['gps','Perangkat GPS',<Radio key="i"/>]] as [AdminTab,string,React.ReactNode][]).map(([key,label,icon])=><button key={key} onClick={()=>setTab(key)} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-semibold [&_svg]:size-4 ${tab===key?'bg-ink text-white':'text-slate-500 hover:bg-slate-50'}`}>{icon}{label}</button>)}</div><div className="mt-auto rounded-2xl bg-slate-50 p-3"><p className="text-xs font-bold">Admin Kota Bandung</p><p className="text-[10px] text-slate-400">admin@traslink.id</p><Button onClick={()=>setView('passenger')} variant="ghost" size="sm" className="mt-2 w-full justify-start"><LogOut/> Keluar dashboard</Button></div></aside>
    <header className="sticky top-0 z-30 flex h-16 items-center justify-between border-b bg-white/90 px-4 backdrop-blur-xl lg:ml-64 lg:px-8"><div className="flex items-center gap-3"><Button variant="ghost" size="icon" className="lg:hidden"><Menu/></Button><div><h1 className="text-base font-extrabold">{tab==='overview'?'Ringkasan Operasional':tab==='routes'?'Manajemen Trayek':tab==='vehicles'?'Data Angkutan Kota':'Perangkat GPS'}</h1><p className="hidden text-[11px] text-slate-400 sm:block">Jumat, 25 September 2026 · Kota Bandung</p></div></div><div className="flex items-center gap-2"><Button onClick={()=>setView('passenger')} variant="outline" size="sm"><MapIcon/> Lihat peta</Button><span className="grid size-9 place-items-center rounded-full bg-ink text-xs font-bold text-white">AF</span></div></header>
    <div className="lg:ml-64"><div className="flex gap-1 overflow-auto border-b bg-white px-4 py-2 lg:hidden">{(['overview','routes','vehicles','gps'] as AdminTab[]).map(t=><Button key={t} onClick={()=>setTab(t)} variant={tab===t?'default':'ghost'} size="sm">{t}</Button>)}</div><div className="mx-auto max-w-7xl p-4 md:p-8">{tab==='overview'&&<Overview setTab={setTab}/>} {tab==='routes'&&<RoutesPanel/>} {tab==='vehicles'&&<VehiclesPanel vehicles={filtered} query={query} setQuery={setQuery} routeFilter={routeFilter} setRouteFilter={setRouteFilter} onAdd={()=>setShowForm(true)} onDelete={(p)=>setVehicles(vehicles.filter(v=>v.plate!==p))}/>} {tab==='gps'&&<GpsPanel/>}</div></div>
    {showForm&&<Modal title="Tambah angkutan kota" close={()=>setShowForm(false)}><div className="grid gap-4"><Field label="Nomor polisi"><Input defaultValue="D 2088 TL"/></Field><Field label="Nama supir"><Input defaultValue="Sopir Baru"/></Field><div className="grid grid-cols-2 gap-3"><Field label="Trayek"><Input defaultValue="03"/></Field><Field label="ID GPS"><Input defaultValue="GPS-TL-016"/></Field></div><Button onClick={addVehicle} className="h-11 bg-coral">Simpan angkot</Button></div></Modal>}{toast&&<div className="fixed bottom-5 right-5 z-50 flex items-center gap-2 rounded-xl bg-ink px-4 py-3 text-sm font-semibold text-white shadow-xl"><Check className="size-4 text-emerald-400"/>{toast}</div>}
  </main>;
}

function Overview({setTab}:{setTab:(t:AdminTab)=>void}) { return <><div className="mb-6 flex items-end justify-between"><div><p className="text-sm text-slate-500">Selamat datang kembali,</p><h2 className="text-2xl font-black tracking-tight md:text-3xl">Transportasi kota dalam satu pantauan.</h2></div><Button onClick={()=>setTab('routes')} className="hidden bg-coral md:flex"><Plus/> Tambah trayek</Button></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4"><StatCard icon={<Route/>} label="Trayek aktif" value="12" change="+2 bulan ini"/><StatCard icon={<BusFront/>} label="Angkot beroperasi" value="87" change="76% armada"/><StatCard icon={<Users/>} label="Jemput hari ini" value="1.284" change="+18,2%"/><StatCard icon={<Activity/>} label="GPS terhubung" value="96%" change="Stabil"/></div><div className="mt-6 grid gap-5 xl:grid-cols-[1.5fr_1fr]"><div className="overflow-hidden rounded-2xl border bg-white"><div className="flex items-center justify-between border-b p-4"><div><h3 className="font-extrabold">Aktivitas trayek</h3><p className="text-xs text-slate-400">Pergerakan armada saat ini</p></div><Button onClick={()=>setTab('routes')} variant="ghost" size="sm">Kelola semua</Button></div><div className="divide-y">{routes.map(r=><div key={r.code} className="flex items-center gap-3 p-4"><span className="grid size-10 place-items-center rounded-xl font-black text-white" style={{background:r.color}}>{r.code}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{r.name}</b><p className="text-xs text-slate-400">via {r.via}</p></div><div className="text-right"><b className="text-sm">{r.active} aktif</b><p className="text-[10px] text-slate-400">dari {r.fleet} armada</p></div></div>)}</div></div><div className="rounded-2xl bg-ink p-5 text-white"><p className="text-xs text-white/50">Permintaan jemput</p><p className="mt-1 text-3xl font-black">142</p><div className="mt-6 flex h-32 items-end gap-2">{[35,48,42,64,54,77,82,68,91,78,94,86].map((h,i)=><span key={i} className="flex-1 rounded-t bg-coral/90" style={{height:`${h}%`,opacity:.45+i*.045}}/>)}</div><div className="mt-2 flex justify-between text-[10px] text-white/35"><span>06.00</span><span>12.00</span><span>18.00</span></div></div></div></>; }

function RoutesPanel() { const [selected,setSelected]=useState(0); const [points,setPoints]=useState(5); return <div className="grid gap-5 xl:grid-cols-[380px_1fr]"><div><div className="mb-4 flex items-center justify-between"><div><h2 className="text-xl font-black">Daftar trayek</h2><p className="text-xs text-slate-400">12 trayek terdaftar</p></div><Button className="bg-coral"><Plus/> Tambah</Button></div><div className="space-y-2">{routes.map((r,i)=><button key={r.code} onClick={()=>setSelected(i)} className={`w-full rounded-2xl border p-4 text-left transition ${selected===i?'border-ink bg-white shadow-sm':'bg-white/60 hover:bg-white'}`}><div className="flex gap-3"><span className="grid size-11 place-items-center rounded-xl font-black text-white" style={{background:r.color}}>{r.code}</span><div className="min-w-0 flex-1"><b className="block truncate text-sm">{r.name}</b><p className="text-xs text-slate-400">{r.stops} halte · {r.fleet} angkot</p></div><MoreHorizontal className="size-4 text-slate-400"/></div></button>)}</div></div><div className="overflow-hidden rounded-2xl border bg-white"><div className="flex flex-wrap items-center justify-between gap-3 border-b p-4"><div><Badge className="mb-1 bg-rose-50 text-coral">Editor rute {routes[selected].code}</Badge><h3 className="font-extrabold">{routes[selected].name}</h3></div><div className="flex gap-2"><Button onClick={()=>setPoints(Math.max(2,points-1))} variant="outline"><Undo2/> Urungkan</Button><Button className="bg-ink"><Check/> Simpan rute</Button></div></div><div className="relative h-[500px]"><MapCanvas routeIndex={selected} editor/><div className="absolute left-4 top-4 z-20 w-48 rounded-xl bg-white/95 p-3 shadow-map"><p className="text-[10px] font-bold uppercase tracking-widest text-slate-400">Petunjuk editor</p><p className="mt-1 text-xs text-slate-600">Klik peta untuk menambah titik. Geser titik untuk mengubah jalur.</p><Button onClick={()=>setPoints(points+1)} size="sm" className="mt-3 w-full bg-coral"><Plus/> Tambah titik ({points})</Button></div></div></div></div>; }

function VehiclesPanel({vehicles,query,setQuery,routeFilter,setRouteFilter,onAdd,onDelete}:{vehicles:typeof initialVehicles;query:string;setQuery:(s:string)=>void;routeFilter:string;setRouteFilter:(s:string)=>void;onAdd:()=>void;onDelete:(p:string)=>void}) { return <><div className="mb-5 flex flex-wrap items-end justify-between gap-3"><div><h2 className="text-xl font-black">Armada angkot</h2><p className="text-xs text-slate-400">Kelola armada pada setiap trayek</p></div><Button onClick={onAdd} className="bg-coral"><Plus/> Tambah angkot</Button></div><div className="overflow-hidden rounded-2xl border bg-white"><div className="flex flex-wrap gap-2 border-b p-4"><div className="relative min-w-56 flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-slate-400"/><Input value={query} onChange={e=>setQuery(e.target.value)} className="pl-9" placeholder="Cari polisi atau supir..."/></div><select value={routeFilter} onChange={e=>setRouteFilter(e.target.value)} className="h-8 rounded-lg border bg-white px-3 text-xs font-semibold"><option>Semua</option>{routes.map(r=><option key={r.code}>{r.code}</option>)}</select></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="p-4">Angkot</th><th className="p-4">Supir</th><th className="p-4">Trayek</th><th className="p-4">GPS</th><th className="p-4">Status</th><th className="p-4 text-right">Aksi</th></tr></thead><tbody className="divide-y">{vehicles.map(v=><tr key={v.plate} className="hover:bg-slate-50"><td className="p-4 font-bold">{v.plate}</td><td className="p-4">{v.driver}</td><td className="p-4"><Badge className="bg-slate-100 text-ink">{v.route}</Badge></td><td className="p-4 font-mono text-xs text-slate-500">{v.gps}</td><td className="p-4"><Badge className={v.status==='Aktif'?'bg-emerald-50 text-emerald-700':'bg-amber-50 text-amber-700'}><span className="size-1.5 rounded-full bg-current"/>{v.status}</Badge></td><td className="p-4"><div className="flex justify-end gap-1"><Button variant="ghost" size="icon-sm"><Edit3/></Button><Button onClick={()=>onDelete(v.plate)} variant="ghost" size="icon-sm" className="text-red-500"><Trash2/></Button></div></td></tr>)}</tbody></table>{vehicles.length===0&&<div className="p-10 text-center text-sm text-slate-400">Tidak ada angkot yang cocok.</div>}</div></div></>; }

function GpsPanel() { const [devices,setDevices]=useState([{id:'GPS-TL-001',imei:'861234050001921',plate:'D 1924 UA',seen:'Baru saja',status:'Online'},{id:'GPS-TL-002',imei:'861234050001922',plate:'D 1842 UB',seen:'12 dtk lalu',status:'Online'},{id:'GPS-TL-008',imei:'861234050001928',plate:'D 1721 UC',seen:'18 mnt lalu',status:'Offline'}]); return <><div className="mb-5 flex items-end justify-between gap-3"><div><h2 className="text-xl font-black">Perangkat GPS</h2><p className="text-xs text-slate-400">Pantau koneksi pelacak armada</p></div><Button onClick={()=>setDevices([...devices,{id:'GPS-TL-016',imei:'861234050001936',plate:'Belum terpasang',seen:'—',status:'Siap'}])} className="bg-coral"><Plus/> Tambah GPS</Button></div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{devices.map(d=><div key={d.id} className="rounded-2xl border bg-white p-4"><div className="flex items-start justify-between"><span className="grid size-10 place-items-center rounded-xl bg-slate-100"><Radio className="size-4"/></span><Badge className={d.status==='Online'?'bg-emerald-50 text-emerald-700':d.status==='Siap'?'bg-blue-50 text-blue-700':'bg-slate-100 text-slate-500'}>{d.status}</Badge></div><h3 className="mt-4 font-extrabold">{d.id}</h3><p className="font-mono text-[10px] text-slate-400">IMEI {d.imei}</p><div className="mt-4 flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p className="text-[10px] text-slate-400">Terpasang pada</p><b className="text-xs">{d.plate}</b></div><div className="text-right"><p className="text-[10px] text-slate-400">Sinyal terakhir</p><b className="text-xs">{d.seen}</b></div></div><div className="mt-3 flex gap-2"><Button variant="outline" size="sm" className="flex-1"><Edit3/> Atur</Button><Button variant="ghost" size="icon-sm"><MoreHorizontal/></Button></div></div>)}</div></>; }

function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="grid gap-1.5 text-xs font-bold text-slate-600">{label}{children}</label>; }
function Modal({title,close,children}:{title:string;close:()=>void;children:React.ReactNode}) { return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/35 p-4 backdrop-blur-sm" onMouseDown={close}><div className="w-full max-w-md rounded-2xl bg-white p-5 shadow-2xl" onMouseDown={e=>e.stopPropagation()}><div className="mb-5 flex items-center justify-between"><h2 className="text-lg font-black">{title}</h2><Button onClick={close} variant="ghost" size="icon"><X/></Button></div>{children}</div></div>; }

export default function Home() { const [view,setView]=useState<View>('passenger'); if(view==='driver') return <DriverView setView={setView}/>; if(view==='admin') return <AdminView setView={setView}/>; return <PassengerView setView={setView}/>; }
