import { NextResponse } from 'next/server';
import { and, desc, eq, gt, inArray } from 'drizzle-orm';
import { z } from 'zod';
import { db } from '@/lib/db';
import { pickupRequests, transitRoutes, users } from '@/db/schema';
import { requireRole } from '@/lib/auth';
import { distanceToRoute } from '@/lib/geo';

export async function GET(){try{const user=await requireRole(['ADMIN','DRIVER','PASSENGER']);const conditions=user.role==='PASSENGER'?and(eq(pickupRequests.passengerId,user.id),inArray(pickupRequests.status,['WAITING','ACCEPTED'])):and(inArray(pickupRequests.status,['WAITING','ACCEPTED']),gt(pickupRequests.expiresAt,new Date()));const rows=await db().select({id:pickupRequests.id,status:pickupRequests.status,direction:pickupRequests.direction,latitude:pickupRequests.latitude,longitude:pickupRequests.longitude,distanceToRouteMeters:pickupRequests.distanceToRouteMeters,createdAt:pickupRequests.createdAt,expiresAt:pickupRequests.expiresAt,passengerName:users.name,passengerPhone:users.phone,routeId:pickupRequests.routeId,routeCode:transitRoutes.code,acceptedByVehicleId:pickupRequests.acceptedByVehicleId}).from(pickupRequests).innerJoin(users,eq(pickupRequests.passengerId,users.id)).innerJoin(transitRoutes,eq(pickupRequests.routeId,transitRoutes.id)).where(conditions).orderBy(desc(pickupRequests.createdAt));return NextResponse.json({pickups:rows});}catch(error){if(error instanceof Response)return error;return NextResponse.json({error:'Gagal memuat permintaan'},{status:500})}}
const input=z.object({routeId:z.string().uuid(),direction:z.enum(['A','B']),latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180)});
export async function POST(request:Request){try{const user=await requireRole(['PASSENGER','ADMIN']);const parsed=input.safeParse(await request.json());if(!parsed.success)return NextResponse.json({error:'Lokasi tidak valid'},{status:400});const [route]=await db().select().from(transitRoutes).where(eq(transitRoutes.id,parsed.data.routeId)).limit(1);if(!route)return NextResponse.json({error:'Trayek tidak ditemukan'},{status:404});const path=parsed.data.direction==='A'?route.pathA:route.pathB;const distance=Math.round(distanceToRoute({lat:parsed.data.latitude,lng:parsed.data.longitude},path));if(distance>150)return NextResponse.json({error:`Lokasi ${distance} m dari trayek. Batas maksimal 150 m.`,distance},{status:422});await db().update(pickupRequests).set({status:'CANCELLED',updatedAt:new Date()}).where(and(eq(pickupRequests.passengerId,user.id),eq(pickupRequests.status,'WAITING')));const [pickup]=await db().insert(pickupRequests).values({...parsed.data,passengerId:user.id,distanceToRouteMeters:distance,expiresAt:new Date(Date.now()+15*60_000)}).returning();return NextResponse.json({pickup},{status:201});}catch(error){if(error instanceof Response)return error;return NextResponse.json({error:error instanceof Error?error.message:'Gagal meminta jemput'},{status:500})}}
